### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by austinsmorris** [austinsmorris/velocy_pack#38]
** Value Types

- [ ] `0x00`        : none - this indicates absence of any type and value, this is not allowed in VPack values
- [ ] `0x01`        : empty array
- [ ] `0x02`        : array without index table (all subitems have the same byte length), 1-byte byte length
- [ ] `0x03`        : array without index table (all subitems have the same byte length), 2-byte byte length
- [ ] `0x04`        : array without index table (all subitems have the same byte length), 4-byte byte length
- [ ] `0x05`        : array without index table (all subitems have the same byte length), 8-byte byte length
- [ ] `0x06`        : array with 1-byte index table offsets, bytelen and # subvals
- [ ] `0x07`        : array with 2-byte index table offsets, bytelen and # subvals
- [ ] `0x08`        : array with 4-byte index table offsets, bytelen and # subvals
- [ ] `0x09`        : array with 8-byte index table offsets, bytelen and # subvals
- [ ] `0x0a`        : empty object
- [ ] `0x0b`        : object with 1-byte index table offsets, sorted by attribute name, 1-byte bytelen and # subvals
- [ ] `0x0c`        : object with 2-byte index table offsets, sorted by attribute name, 2-byte bytelen and # subvals
- [ ] `0x0d`        : object with 4-byte index table offsets, sorted by attribute name, 4-byte bytelen and # subvals
- [ ] `0x0e`        : object with 8-byte index table offsets, sorted by attribute name, 8-byte bytelen and # subvals
- [ ] `0x0f`        : object with 1-byte index table offsets, not sorted by attribute name, 1-byte bytelen and # subvals - OBSOLETE
- [ ] `0x10`        : object with 2-byte index table offsets, not sorted by attribute name, 2-byte bytelen and # subvals - OBSOLETE
- [ ] `0x11`        : object with 4-byte index table offsets, not sorted by attribute name, 4-byte bytelen and # subvals - OBSOLETE
- [ ] `0x12`        : object with 8-byte index table offsets, not sorted by attribute name, 8-byte bytelen and # subvals - OBSOLETE
- [ ] `0x13`        : compact array, no index table
- [ ] `0x14`        : compact object, no index table
- [ ] `0x15`-`0x16` : reserved
- [ ] `0x17`        : illegal - this type can be used to indicate a value that is illegal in the embedding application
- [ ] `0x18`        : null
- [ ] `0x19`        : false
- [ ] `0x1a`        : true
- [ ] `0x1b`        : double IEEE-754, 8 bytes follow, stored as little endian uint64 equivalent
- [ ] `0x1c`        : UTC-date in milliseconds since the epoch, stored as 8 byte signed int, little endian, two's complement
- [ ] `0x1d`        : external (only in memory): a char* pointing to the actual place in memory, where another VPack item resides, not allowed in VPack values on disk or on the network
- [ ] `0x1e`        : minKey, nonsensical value that compares < than all other values
- [ ] `0x1f`        : maxKey, nonsensical value that compares > than all other values
- [ ] `0x20`-`0x27` : signed int, little endian, 1 to 8 bytes, number is V - `0x1f`, two's complement
- [ ] `0x28`-`0x2f` : uint, little endian, 1 to 8 bytes, number is V - `0x27`
- [ ] `0x30`-`0x39` : small integers 0, 1, ... 9
- [ ] `0x3a`-`0x3f` : small negative integers -6, -5, ..., -1
- [ ] `0x40`-`0xbe` : UTF-8-string, using V - `0x40` bytes (not Unicode characters!), length 0 is possible, so `0x40` is the empty string, maximal length is 126, note that strings here are not zero-terminated and may contain NUL bytes
- [ ] `0xbf`        : long UTF-8-string, next 8 bytes are length of string in bytes (not Unicode characters) as little endian unsigned integer, note that long strings are not zero-terminated and may contain NUL bytes
- [ ] `0xc0`-`0xc7` : binary blob, next V - `0xbf` bytes are the length of blob in bytes, note that binary blobs are not zero-terminated
- [ ] `0xc8`-`0xcf` : positive long packed BCD-encoded float, V - `0xc7` bytes follow  that encode in a little endian way the length of the  mantissa in bytes. Directly after that follow 4 bytes encoding the (power of 10) exponent, by which the mantissa is to be multiplied, stored as little endian two's complement signed 32-bit integer. After that, as many bytes follow as the length information at the beginning has specified, each byte encodes two digits in big-endian packed BCD. Example: 12345 decimal can be encoded as `c8 03 00 00 00 00 01 23 45` or `c8 03 ff ff ff ff 12 34 50`
- [ ] `0xd0`-`0xd7` : negative long packed BCD-encoded float, V - `0xcf` bytes follow that encode in a little endian way the length of the mantissa in bytes. After that, same as positive long packed BCD-encoded float above.
- [ ] `0xd8`-`0xed` : reserved
- [ ] `0xee`-`0xef` : value tagging for logical types
- [ ] `0xf0`-`0xff` : custom types
